u20436310_HW04/Controllers/FamerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using u20436310_HW04.Models;

namespace u20436310_HW04.Controllers
{
    public class FamerController : Controller
    {
        public IActionResult Index()
        {
            List<Farmer> farmerslist = new List<Farmer>();

            Farmer farmer1 = new Farmer("https://i.kym-cdn.com/photos/images/newsfeed/001/445/963/523.jpg", "John's Produce", "John Williams is a 40-year-old tea maker who enjoys duck herding, eating and football. He is friendly and gentle, but can also be very sadistic and a bit unintelligent. He is addicted to chocolate, something which his friend Lulu Thea Morrison pointed out when he was 15.The problem intensified in 2001.John has lost two jobs as a result of his addiction, specifically: golf caddy and kitchen assistant.He is an Australian Christian who defines himself as straight.He finished school and then left academia.");
            Farmer farmer2 = new Farmer("https://media.istockphoto.com/photos/portrait-of-farmer-standing-in-soybean-field-at-sunset-picture-id1198012795", "Fred's Farm", "Fred Powell is a 40-year-old golf caddy who enjoys listening to music, duck herding and worship. He is friendly and gentle, but can also be very sadistic and a bit unintelligent. He is addicted to video games, something which his friend Keiran Quinn Gibson pointed out when he was 17.The problem intensified in 2001.In 2016, Fred lost his job as a trainee tradesperson as a result of his addiction.He is an American Christian who defines himself as straight.He finished school and then left academia.");
            Farmer farmer3 = new Farmer("https://media.istockphoto.com/id/493551400/photo/winemaker-in-vineyard.webp?s=612x612&w=is&k=20&c=UjLaBoV4jmzjNasdKKm2ZkkfjRz2SbOS38fcP8pnHJA=", "Timmy's Livestock and Produce", "Timmy Anderson is a 61-year-old town counsellor who enjoys eating out, meditation and playing card games. He is kind and inspiring, but can also be very cowardly and a bit disloyal. He is an American Christian who defines himself as straight.He finished school and then left academia.He is obsessed with organic vegetables.Physically, Timmy is slightly overweight but otherwise in good shape.He is tall with cocao skin, black hair and brown eyes.");

            farmerslist.Add(farmer1);
            farmerslist.Add(farmer2);
            farmerslist.Add(farmer3);

            return View(farmerslist);
        }
        public IActionResult Add()
        {
            return View();
        }
    }
}

u20436310_HW04/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using u20436310_HW04.Models;

namespace u20436310_HW04.Controllers
{
    public class LocationController : Controller
    {
        public IActionResult Index()
        {
            List<Location> locationslist = new List<Location>();

            Location location1 = new Location("https://image.shutterstock.com/image-photo/durban-kwazulu-natal-south-africa-600w-1708786963.jpg", "178 Gerorge Street","Umhlanga Rocks","KwaZulu-Natal","Central location of the First For Woman refugee camp.");
            Location location2 = new Location("https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/South_Africa-Johannesburg-Hillbrow001.jpg/800px-South_Africa-Johannesburg-Hillbrow001.jpg", "51 Fairlady Way", "Hillbrow", "Gauteng", "Homeless Shelter catering for all.");

            locationslist.Add(location1);
            locationslist.Add(location2);
            return View(locationslist);
        }

        public IActionResult Add()
        {
            return View();
        }
    }
}

u20436310_HW04/Controllers/PackageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using u20436310_HW04.Models;

namespace u20436310_HW04.Controllers
{
    public class PackageController : Controller
    {
        public IActionResult Index()
        {
            List<Package> packageslist = new List<Package>();

            Package package1 = new Package("Chicken Deluxe Package","Delicious Chicken", "https://www.shopriteholdings.co.za/content/dam/MediaPortal/article1/2022/new-rotisserie-chicken-boxes-/new-rotisserie-chicken-boxes.jpg/jcr:content/renditions/cq5dam.web.1280.1280.jpeg", 65.99, new DateTime(2022,08,19), new DateTime(2022,08,22));
            Package package2 = new Package("Full Soup Package", "Soup that is ready made.", "https://www.eatwell101.com/wp-content/uploads/2020/02/chicken-soup-recipe-3.jpg", 40.99, new DateTime(2022, 08, 21), new DateTime(2022, 08, 24));
            Package package3 = new Package("Fresh Produce Package", "Full package with vaying produce", "https://images.unsplash.com/photo-1464226184884-fa280b87c399?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80", 25.40, new DateTime(2022, 08, 15), new DateTime(2022, 08, 20));
            Package package4 = new Package("Turducken", "Turkey, duck and chicken", "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6045938.jpg", 420.00, new DateTime(2022, 08, 20), new DateTime(2022, 08, 24));

            packageslist.Add(package1);
            packageslist.Add(package2);
            packageslist.Add(package3);
            packageslist.Add(package4);

            return View(packageslist);
        }
        public IActionResult Details()
        {
            List<Farmer> farmers = new List<Farmer>();
            return View(farmers);
        }
    }
}

u20436310_HW04/Controllers/SupermarketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using u20436310_HW04.Models;

namespace u20436310_HW04.Controllers
{
    public class SupermarketController : Controller
    {
        public IActionResult Index()
        {
            List<Supermarket> supermarketslist = new List<Supermarket>();

            Supermarket supermarket1 = new Supermarket("https://flash.za.com/wp-content/uploads/1970/01/boxer-superstores1.jpg", "Boxer Superstores", "Boxer is one of the fastest growing discount supermarkets in Southern Africa. With a cemented set of ‘people centered’ goals and values, we have positioned ourselves as ‘Africa’s Favourite Discount Supermarket’ - a discounter that caters for the needs of the enlarged middle to lower income consumer market. Since our beginnings, more than four decades ago in 1977, in KwaZulu-Natal’s Empangeni community, the Boxer brand has grown far and wide and includes well defined retail offerings that boast stores spread in every province of South Africa, as well as in the Kingdom of eSwatini (Swaziland).");
            Supermarket supermarket2 = new Supermarket("https://cdn-prd-02.pnp.co.za/sys-master/images/h26/h64/10206546133022/pick-n-pay-header2.png", "Pick 'n Pay", "Pick n Pay is the quintessential family store focused on the customer. Since 1967 when consumer champion Raymond Ackerman purchased the first few stores, the Ackerman family’s vision has grown and expanded to now encompass stores in South Africa, Namibia, Botswana, Zambia, Mozambique, Mauritius, Swaziland and Lesotho. Additionally Pick n Pay owns a 49% share of a Zimbabwean supermarket business, TM Supermarkets. Our offer to customers focuses on groceries, clothing and general merchandise, but also includes additional value-added services to cater for our customers’ expectations and evolving needs. To ensure a convenient and accessible shopping experience the Group operates across multiple store formats, both franchised and owned.");

            supermarketslist.Add(supermarket1);
            supermarketslist.Add(supermarket2);

            return View(supermarketslist);
        }
    }
}

u20436310_HW04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - u20436310_HW04</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <meta name="author" content="Dilano Adams" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">u20436310_HW04</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Package" asp-action="Index">Packages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Famer" asp-action="Index">Farmers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - u20436310_HW04 - <a asp-area="" asp-controller="Supermarket" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>